name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install clang-format
      run: sudo apt update && sudo apt install -y clang-format

    - name: Check formatting
      run: |
        find . -name "*.cpp" -o -name "*.hpp" -o -name "*.h" -o -name "*.c" -o -name "*.def" | \
        xargs clang-format --dry-run -Werror

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        preset:
          - linux-gcc-debug
          - linux-gcc-release

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          cmake \
          ninja-build \
          clang-tidy-20 \
          cppcheck \
          software-properties-common

        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt update
        sudo apt install -y gcc-14 g++-14 libstdc++-14-dev

        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
        sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-20 60
        sudo update-alternatives --set clang-tidy /usr/bin/clang-tidy-20

        gcc --version
        g++ --version
        clang-tidy --version
        clang-tidy-20 --version

        which clang-tidy
        which clang-tidy-20
        sudo update-alternatives --config clang-tidy


        sudo ldconfig

        sudo apt update
        sudo apt upgrade -y
    
    - name: Configure CMake
      run: cmake --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build --preset ${{ matrix.preset }} -j

    - name: Run Tests
      run: ctest --preset ${{ matrix.preset }} --output-on-failure

